
#ifndef DEFINESRECTANGULAR_HPP
#define DEFINESRECTANGULAR_HPP

#define DIMX_REC 20
#define DIMY_REC 60
#define LINES_REC 2
#define COLUMNS_REC 3
#define NWORKERS_REC LINES_REC*COLUMNS_REC
#define PROC_DIMX_REC DIMX_REC/LINES_REC
#define PROC_DIMY_REC DIMY_REC/COLUMNS_REC

#endif
